import React, { useState, useEffect } from 'react';
import { getBills } from '../services/api';

function Bills() {
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadBills();
  }, []);

  const loadBills = async () => {
    try {
      setLoading(true);
      const response = await getBills();
      setBills(response.data.bills || []);
    } catch (err) {
      setError('Failed to load bills');
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status) => {
    const colors = {
      'paid': 'bg-green-100 text-green-800',
      'sent': 'bg-blue-100 text-blue-800',
      'pending': 'bg-yellow-100 text-yellow-800',
      'overdue': 'bg-red-100 text-red-800'
    };
    return colors[status] || 'bg-gray-100 text-gray-800';
  };

  if (loading) return <div className="text-center py-10">Loading bills...</div>;

  return (
    <div>
      <h1 className="text-3xl font-bold text-hydro-deep-aqua mb-6">Bills</h1>

      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
          {error}
        </div>
      )}

      {bills.length === 0 ? (
        <div className="card text-center py-12">
          <p className="text-xl text-gray-600">No bills available yet</p>
          <p className="text-sm text-gray-500 mt-2">Bills will appear here once generated by administrators</p>
        </div>
      ) : (
        <div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="card bg-gradient-to-br from-green-500 to-green-600 text-white">
              <p className="text-sm mb-1">Total Paid</p>
              <p className="text-2xl font-bold">
                ${bills.filter(b => b.status === 'paid').reduce((sum, b) => sum + parseFloat(b.total_amount), 0).toFixed(2)}
              </p>
            </div>
            <div className="card bg-gradient-to-br from-yellow-500 to-yellow-600 text-white">
              <p className="text-sm mb-1">Pending</p>
              <p className="text-2xl font-bold">
                ${bills.filter(b => b.status === 'pending' || b.status === 'sent').reduce((sum, b) => sum + parseFloat(b.total_amount), 0).toFixed(2)}
              </p>
            </div>
            <div className="card bg-gradient-to-br from-red-500 to-red-600 text-white">
              <p className="text-sm mb-1">Overdue</p>
              <p className="text-2xl font-bold">
                ${bills.filter(b => b.status === 'overdue').reduce((sum, b) => sum + parseFloat(b.total_amount), 0).toFixed(2)}
              </p>
            </div>
          </div>

          <div className="card">
            <h2 className="text-xl font-semibold mb-4">Bill History</h2>
            
            <div className="overflow-x-auto">
              <table className="min-w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Bill Period</th>
                    <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Usage (CCF)</th>
                    <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Amount</th>
                    <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Due Date</th>
                    <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {bills.map((bill) => (
                    <tr key={bill.id} className="hover:bg-gray-50">
                      <td className="px-4 py-2 text-sm">
                        {bill.billing_period_start} to {bill.billing_period_end}
                      </td>
                      <td className="px-4 py-2 text-sm">{parseFloat(bill.total_usage_ccf).toFixed(2)}</td>
                      <td className="px-4 py-2 text-sm font-semibold text-hydro-deep-aqua">
                        ${parseFloat(bill.total_amount).toFixed(2)}
                      </td>
                      <td className="px-4 py-2 text-sm">{bill.due_date}</td>
                      <td className="px-4 py-2 text-sm">
                        <span className={`px-2 py-1 rounded text-xs font-semibold ${getStatusColor(bill.status)}`}>
                          {bill.status.toUpperCase()}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Bills;